version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p12345 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # For persistent data, add volumes if desired:
    # volumes:
    #   - ./data/mysql:/var/lib/mysql
